name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6

      - name: Install dependencies
        working-directory: jsmn-go
        run: go mod tidy

      - name: Lint with golangci-lint
        working-directory: jsmn-go
        run: golangci-lint run --config ../.golangci.yml

      - name: Test
        working-directory: jsmn-go
        run: go test -v

      - name: Benchmark
        working-directory: jsmn-go
        run: go test -bench .

      - name: Test with Coverage
        working-directory: jsmn-go
        run: go test -coverprofile=coverage.txt -v
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./jsmn-go/coverage.txt
    
      - name: Test with Coverage  # New: Generate coverage file.
        working-directory: jsmn-go
        run: go test -coverprofile=coverage.txt -v

      - name: Upload Coverage to Codecov  # New: Upload file.
        uses: codecov/codecov-action@v4
        with:
          files: ./jsmn-go/coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}  # Optional if public repo.
          verbose: true